on:
  push:
    branches:
      - 'main'

defaults:
  run:
    working-directory: .

env:
  TEST_TAG: p1/spotadvisor:test

jobs:
  docker:
    runs-on: self-hosted
    name: Build and test spotadvisor
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build against buildx
        uses: docker/build-push-action@v2
        with:
          builder: buildx
          context: .
          push: false
          tags: ${{ env.TEST_TAG }}

      - name: json-test
        run: |
          docker run -it --rm ${{ env.TEST_TAG }} python spotadvisor.py --maxintcode 2 --mincpus 48  --region=us-west-2 --intelonly --format json

      - name: csv-test
        run: |
          docker run -it --rm ${{ env.TEST_TAG }} python spotadvisor.py --maxintcode 2 --mincpus 48  --region=us-west-2 --intelonly --format csv
    
      - name: table-test
        run: |
          docker run -it --rm ${{ env.TEST_TAG }} python spotadvisor.py --maxintcode 2 --mincpus 48  --region=us-west-2 --intelonly --format table
