on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: p1/spotadvisor:test

jobs:
  docker:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        uses: docker/setup-buildx-action@v1
        id: builder

      - name: Build against builder1
        uses: docker/build-push-action@v2
        with:
          builder: builder
          context: .
          push: false
          tags: ${{ env.TEST_TAG }}

      - name: json-test
        run: |
          docker run --it --rm ${{ env.TEST_TAG }} python spotadvisor.py --maxintcode 2 --mincpus 48  --region=us-west-2 --intelonly --format json

      - name: csv-test
        run: |
          docker run --it --rm ${{ env.TEST_TAG }} python spotadvisor.py --maxintcode 2 --mincpus 48  --region=us-west-2 --intelonly --format csv
    
      - name: table-test
        run: |
          docker run --it --rm ${{ env.TEST_TAG }} python spotadvisor.py --maxintcode 2 --mincpus 48  --region=us-west-2 --intelonly --format table
